name: Docker Build Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t react-vite-app:${{ github.sha }} .
          
      - name: Cleanup
        if: always()
        run: |
          docker rmi react-vite-app:${{ github.sha }} || true